#!/usr/bin/env python3

import time
import colors as c
print(c.clear)
snake = '''

SNAKEA SNAKEA

'''
while True:

    for verse in range (5):
    
        for badger in range(12):
            print('Badgers!')
            time.sleep(0.38)

        for mushroom in range(2):
            print('Muuussshroom') 
            time.sleep(0.8)
            print(c.clear)
        if mushroom in range (3):
                print(snake)
                time.sleep(6)
                print(c.clear)
