#!/usr/bin/env python3

alex = 'I enjoy {} walks on the beach, getting rained on by {}
and bumped into a {}. I really like milk with
{} and romantic {}. I also won a food eating contest with
{}. My freind is {} awesome, (but she has bad grades) 
{} when I am not busy with my car, or work
(I am a {}.) I am looking for {} and beauty in the form
of a {} goddess. She should have the physique of
{} and the {} of {}. I would prefer if she could
cook, clean, and wash my {}. I know I dont look
cool in my picture, but it was cu by my cat
and i had to tape it back up.'
                                                                
print(alex)
