#!/usr/bin/env python3
import colors as c
from utils import ask

print(c.clear)
print(c.green + '''
    welcome to my maddlib
    ''' + c.reset )

text = """I like going to the {Description} mall and eating at the rainforest cafe
having a hotdog. I also got some {Adjective} desert that was made of frozen {Liquid1}. 
My friend {Friend} works at the mall. I drove away from the mall in my {Type of car} 
and my car is coverd in {Food}. I like my drinks mixed with {Liquid2}."""
                                                                
title = text.splitlines()[0]


words = {
    'Description': None,
    'Adjective': None,
    'Liquid1': None,
    'Friend': None,
    'Type of car': None,
    'Food': None,
    'Liquid2': None

}

for keyword in words:
    words[keyword] = c.green + ask(keyword + ':' + c.reset )

print(text.format(**words))


