#!/usr/bin/env python3
import time
import colors as c

print(c.clear + c.green + '''
Multiplication tables
''' + c.reset)
number = input('Which number?  ')

table = input('How many tables do you want? ')
print('''Here are your 
''' + number + "'s tables")
for count in range(0,int(table) + 1):
    print(c.magenta + str(count) + c.reset + ' x ' + number, end=' = ' + c.red)
    print(int(number) * count)
    

