#!/usr/bin/env python3

import time
import colors as c

print(c.clear)

print(c.red + "If you want to quit type Ctrl c")
hundredths = 0
seconds = 0
minutes = 0
hours = 0
mesg = c.clear + c. magenta + "If you want to quit type Ctrl c" + c.reset
try:
    while True:
        print(mesg + '{:02}:{:02}:{:02}.{:02}' .format(hours,minutes,seconds,hundredths))     
        print(hours)
        print(minutes)
        print(seconds)
        print(hundredths)
        #print(c.magenta + 'It has been' , hundredths , ' hundredths')
        #print(c.blue + str(seconds) + c.magenta + 'It has been' , seconds , ' seconds')
        time.sleep(0.01)
        hundredths += 1
        if hundredths == 100:
            print(seconds)
            hundredths = 0
            seconds += 1
        if seconds == 60:
            print(minutes)
            seconds = 0
            minutes += 1
        if minutes == 60:
            print(hours)
            minutes = 0
            hours += 1

except KeyboardInterrupt:
    print(c.green + '\b\bsee you later' + c.reset)
    exit()


