#!/usr/bin/python3

import colors as c

question1 = 'Do you like waffles?'
question2 = 'Do you like pancakes?'
question3 = 'Do you like french toast?'

print(c.clear + c.blue + question1 + c.reset)
answer = input('->')
if answer == 'no':
    print('Well we like we like waffles')
    exit()
if answer == 'yes':
    print(c.clear + c.red + question2 + c.reset)
    answer = input('->')   
    if answer == 'no':
        print('Well we like we like pancakes')
        exit()
    if answer == 'yes':
        print(c.clear + c.magenta + question3 + c.reset)
        answer = input('->')
        if answer == 'yes':
            print(c.green + 'Do Do, Do Cant wait to have a mouthfull')   
        if answer == 'no':
            print('Well we like French Toast')
            exit()
