#!/usr/bin/env python3

import time
import colors as c
while True:
    for verse in range (2):
        for badger in range (11):
            print('badger')
            time.sleep(.38)
        for mush in range(2):
            print('mushroom')
            time.sleep(1)
    for snake in range(2):
        print('SNAKE SNAKE')
        time.sleep(2)
