#!/usr/bin/env python3

import colors as c
import time
import random

sides = ['side 1','side 2','side 3','side 4','side 5','side 6']

while True:
    print(c.random_color() + c.random.choice(sides))
    number = input(' ')

